#!/bin/bash
# infrastructure.sh
# Provisions Google Cloud Platform resources for DPR-RC Architecture

set -e

# Configuration
PROJECT_ID=$(gcloud config get-value project)
REGION="us-central1"
REDIS_NAME="dpr-redis"
REPO_NAME="dpr-repo"
BUCKET_NAME="dpr-audit-logs-${PROJECT_ID}"
HISTORY_BUCKET_NAME="dpr-history-data-${PROJECT_ID}"
SERVICE_ACCOUNT="dpr-agent-sa"

echo "Provisioning Infrastructure for Project: $PROJECT_ID in $REGION"

# 1. Enable APIs
echo "Enabling required APIs..."
gcloud services enable \
    run.googleapis.com \
    redis.googleapis.com \
    storage.googleapis.com \
    artifactregistry.googleapis.com \
    logging.googleapis.com \
    cloudbuild.googleapis.com \
    compute.googleapis.com \
    vpcaccess.googleapis.com

# 2. Storage Setup
echo "Creating GCS Buckets..."
gsutil mb -l $REGION gs://${BUCKET_NAME} || echo "Bucket ${BUCKET_NAME} may already exist."
gsutil uniformbucketlevelaccess set on gs://${BUCKET_NAME} || echo "Setting UBLA failed or already set."

gsutil mb -l $REGION gs://${HISTORY_BUCKET_NAME} || echo "Bucket ${HISTORY_BUCKET_NAME} may already exist."
gsutil uniformbucketlevelaccess set on gs://${HISTORY_BUCKET_NAME} || echo "Setting UBLA failed or already set."

# 3. Redis Setup (Messages & State)
# NOTE: Redis and VPC Connector are SKIPPED for HTTP mode deployment
# The system uses direct HTTP calls between Active Controller and Workers
# Redis is only needed for local development with Pub/Sub mode
echo "Skipping Redis and VPC Connector (HTTP mode doesn't require them)..."

# 4. Artifact Registry
echo "Creating Artifact Registry..."
gcloud artifacts repositories create $REPO_NAME \
    --repository-format=docker \
    --location=$REGION \
    --description="DPR-RC Container Repository" \
    || echo "Repository $REPO_NAME may already exist."

# 5. IAM Setup
echo "Creating Service Account..."
gcloud iam service-accounts create $SERVICE_ACCOUNT \
    --display-name="DPR RC Agent Service Account" \
    || echo "Service Account $SERVICE_ACCOUNT may already exist."

SA_EMAIL="${SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com"

# Grant permissions
gcloud projects add-iam-policy-binding $PROJECT_ID \
    --member="serviceAccount:${SA_EMAIL}" \
    --role="roles/storage.objectAdmin"

gcloud projects add-iam-policy-binding $PROJECT_ID \
    --member="serviceAccount:${SA_EMAIL}" \
    --role="roles/logging.logWriter"

gcloud projects add-iam-policy-binding $PROJECT_ID \
    --member="serviceAccount:${SA_EMAIL}" \
    --role="roles/run.invoker"

# 6. Deploy Commands
echo "Infrastructure provisioning complete."
echo "Note: deploy_commands.sh already exists with HTTP-based configuration."
echo "No need to overwrite it."
# The deploy_commands.sh is maintained separately with HTTP mode configuration
# and should not be auto-generated by this script.
